spring:
  application:
    name: store-auth

management:
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: [ 'prometheus' ]
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

store:
  jwt:
    issuer: "In5pEr"
    secretKey: "uHmoVnHjlsU9bJTG47I8KXItcrAlnoCsBXXqhaCgFKkWXxLQmA3VumYK3Z8zPhk8Tgcy45HzHmOIYlf3Wr3t7QAoeIZlQncaYfTckEfq3Gh6UZT0PIpZz9vpta7bOfFI"
    duration: 31536000000 # 365 days in miliseconds